workflows:
  android-workflow:
    name: Android Build

    environment:
      flutter: stable

    scripts:
      - name: Extract android_files.zip
        script: |
          unzip -o android_files.zip
          if [ -d "android/android" ]; then
            mv android/android/* android/
            rmdir android/android
          fi

      - name: Get Flutter packages
        script: flutter pub get

      - name: Build APK
        script: flutter build apk --release

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
